version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_PASSWORD: password 
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: install dependencies
          command: |
            gem install bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: cp .circleci/database.yml config/database.yml
      - run: cp .circleci/application.yml config/application.yml
      - run: RAILS_ENV=test rails db:create
      - run: RAILS_ENV=test rails db:migrate

      - run:
          name: run tests
          command: RAILS_ENV=test bundle exec rspec

      # run code_analysis!
      - run:
          name: run code analysis
          command: RAILS_ENV=test bundle exec rubocop app config lib spec